"""empty message

Revision ID: 01db93e9a7e9
Revises: 71d9d0f406f9
Create Date: 2018-07-28 13:09:15.645112

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '01db93e9a7e9'
down_revision = '71d9d0f406f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('cuisine_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['cuisine_id'], ['cuisine.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurant_association_id'), 'restaurant_association', ['id'], unique=False)
    op.drop_table('association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('restaurant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('collection_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cuisine_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], name='association_collection_id_fkey'),
    sa.ForeignKeyConstraint(['cuisine_id'], ['cuisine.id'], name='association_cuisine_id_fkey'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], name='association_restaurant_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='association_pkey')
    )
    op.drop_index(op.f('ix_restaurant_association_id'), table_name='restaurant_association')
    op.drop_table('restaurant_association')
    # ### end Alembic commands ###
