"""empty message

Revision ID: 1f7e6271b1c9
Revises: 5bb759a8bba4
Create Date: 2018-08-15 19:44:49.201519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f7e6271b1c9'
down_revision = '5bb759a8bba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cab_booking', sa.Column('total_days', sa.Integer(), nullable=True))
    op.add_column('cab_deal', sa.Column('driver_daily_allowance_charge', sa.DECIMAL(), nullable=True))
    op.add_column('cab_deal', sa.Column('driver_per_hr_allowance_charge', sa.DECIMAL(), nullable=True))
    op.drop_column('cab_deal', 'driver_night_allowance_charge')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cab_deal', sa.Column('driver_night_allowance_charge', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_column('cab_deal', 'driver_per_hr_allowance_charge')
    op.drop_column('cab_deal', 'driver_daily_allowance_charge')
    op.drop_column('cab_booking', 'total_days')
    # ### end Alembic commands ###
