"""empty message

Revision ID: 25aaae0275d6
Revises: e91a8ebd12d4
Create Date: 2018-08-05 17:32:22.473315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25aaae0275d6'
down_revision = 'e91a8ebd12d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotel', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotel', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
