"""empty message

Revision ID: 29424b81dc04
Revises: 5e177719a2f0
Create Date: 2018-07-07 15:31:36.786245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29424b81dc04'
down_revision = '5e177719a2f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotel', sa.Column('category', sa.String(), nullable=True))
    op.add_column('room', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'image_url')
    op.drop_column('hotel', 'category')
    # ### end Alembic commands ###
