"""empty message

Revision ID: 2cc88a062410
Revises: cc1b09b3b777
Create Date: 2018-08-10 01:16:05.877485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cc88a062410'
down_revision = 'cc1b09b3b777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cab', sa.Column('rating', sa.DECIMAL(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cab', 'rating')
    # ### end Alembic commands ###
