"""empty message

Revision ID: 303120bc6c13
Revises: c9e7fbc2eb30
Create Date: 2018-08-22 18:26:53.990742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303120bc6c13'
down_revision = 'c9e7fbc2eb30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurant', 'mode_of_payment',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurant', 'mode_of_payment',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
