"""empty message

Revision ID: 37439bfa0a67
Revises: 318f1c63df45
Create Date: 2018-06-23 18:35:19.357728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37439bfa0a67'
down_revision = '318f1c63df45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('facility_hotel_id_key', 'facility', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('facility_hotel_id_key', 'facility', ['hotel_id'])
    # ### end Alembic commands ###
