"""empty message

Revision ID: 3d1a649fe4bd
Revises: 01b29464ab8a
Create Date: 2018-06-16 00:44:40.038755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d1a649fe4bd'
down_revision = '01b29464ab8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('website_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('website_room_id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['website_id'], ['website.id'], ),
    sa.PrimaryKeyConstraint('id', 'website_room_id')
    )
    op.create_index(op.f('ix_website_room_id'), 'website_room', ['id'], unique=False)
    op.create_index(op.f('ix_website_room_website_room_id'), 'website_room', ['website_room_id'], unique=True)
    op.add_column('price', sa.Column('website_room_id', sa.Integer(), nullable=True))
    op.drop_constraint('price_website_id_fkey', 'price', type_='foreignkey')
    op.drop_constraint('price_room_id_fkey', 'price', type_='foreignkey')
    op.create_foreign_key(None, 'price', 'website_room', ['website_room_id'], ['website_room_id'])
    op.drop_column('price', 'room_id')
    op.drop_column('price', 'website_id')
    op.drop_constraint('website_room_id_fkey', 'website', type_='foreignkey')
    op.drop_column('website', 'room_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('website', sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('website_room_id_fkey', 'website', 'room', ['room_id'], ['id'])
    op.add_column('price', sa.Column('website_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('price', sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'price', type_='foreignkey')
    op.create_foreign_key('price_room_id_fkey', 'price', 'room', ['room_id'], ['id'])
    op.create_foreign_key('price_website_id_fkey', 'price', 'website', ['website_id'], ['id'])
    op.drop_column('price', 'website_room_id')
    op.drop_index(op.f('ix_website_room_website_room_id'), table_name='website_room')
    op.drop_index(op.f('ix_website_room_id'), table_name='website_room')
    op.drop_table('website_room')
    # ### end Alembic commands ###
