"""empty message

Revision ID: 4012320fd1d0
Revises: 353c55f3a963
Create Date: 2018-07-24 00:57:48.674867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4012320fd1d0'
down_revision = '353c55f3a963'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('breakfast', sa.Boolean(), nullable=True),
    sa.Column('lunch', sa.Boolean(), nullable=True),
    sa.Column('dinner', sa.Boolean(), nullable=True),
    sa.Column('cafe', sa.Boolean(), nullable=True),
    sa.Column('lounge', sa.Boolean(), nullable=True),
    sa.Column('family', sa.Boolean(), nullable=True),
    sa.Column('bars', sa.Boolean(), nullable=True),
    sa.Column('nightlife', sa.Boolean(), nullable=True),
    sa.Column('street_stalls', sa.Boolean(), nullable=True),
    sa.Column('pocket_friendly', sa.Boolean(), nullable=True),
    sa.Column('diet', sa.Boolean(), nullable=True),
    sa.Column('luxury', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id')
    )
    op.create_index(op.f('ix_menu_id'), 'menu', ['id'], unique=False)
    op.add_column('restaurant', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant', 'price')
    op.drop_index(op.f('ix_menu_id'), table_name='menu')
    op.drop_table('menu')
    # ### end Alembic commands ###
