"""empty message

Revision ID: 412d5e371a0c
Revises: 4fd2e1e7317e
Create Date: 2018-07-29 16:22:29.666359

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '412d5e371a0c'
down_revision = '4fd2e1e7317e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    op.drop_table('tag')
    op.add_column('hotel', sa.Column('phone', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'hotel', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hotel', type_='unique')
    op.drop_column('hotel', 'phone')
    op.create_table('tag',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('restaurant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('breakfast', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('lunch', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('dinner', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('cafe', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('lounge', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('family', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('bars', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('nightlife', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('street_stalls', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('pocket_friendly', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('diet', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('luxury', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tag_pkey'),
    sa.UniqueConstraint('restaurant_id', name='tag_restaurant_id_key')
    )
    op.create_table('association',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('restaurant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dish_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('collection_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cuisine_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='association_pkey')
    )
    # ### end Alembic commands ###
