"""empty message

Revision ID: 46e562df4b4b
Revises: 565bfdcbb0d8
Create Date: 2018-06-16 17:56:27.379927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46e562df4b4b'
down_revision = '565bfdcbb0d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('amenity', sa.Column('Room_cleaning_service', sa.Boolean(), nullable=True))
    op.add_column('amenity', sa.Column('banquets', sa.Boolean(), nullable=True))
    op.add_column('amenity', sa.Column('child_baby_cot', sa.Boolean(), nullable=True))
    op.add_column('amenity', sa.Column('conference_room', sa.Boolean(), nullable=True))
    op.add_column('amenity', sa.Column('doorman', sa.Boolean(), nullable=True))
    op.add_column('amenity', sa.Column('express_check_in_out', sa.Boolean(), nullable=True))
    op.add_column('amenity', sa.Column('hairdresser', sa.Boolean(), nullable=True))
    op.add_column('amenity', sa.Column('indoor_swimming_pool', sa.Boolean(), nullable=True))
    op.add_column('amenity', sa.Column('laundry_service', sa.Boolean(), nullable=True))
    op.add_column('amenity', sa.Column('non_smoking_smoking_rooms', sa.Boolean(), nullable=True))
    op.add_column('amenity', sa.Column('outdoor_swimming_pool', sa.Boolean(), nullable=True))
    op.add_column('amenity', sa.Column('porter_service', sa.Boolean(), nullable=True))
    op.add_column('amenity', sa.Column('terrace', sa.Boolean(), nullable=True))
    op.add_column('amenity', sa.Column('wheelchair_accessible', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('amenity', 'wheelchair_accessible')
    op.drop_column('amenity', 'terrace')
    op.drop_column('amenity', 'porter_service')
    op.drop_column('amenity', 'outdoor_swimming_pool')
    op.drop_column('amenity', 'non_smoking_smoking_rooms')
    op.drop_column('amenity', 'laundry_service')
    op.drop_column('amenity', 'indoor_swimming_pool')
    op.drop_column('amenity', 'hairdresser')
    op.drop_column('amenity', 'express_check_in_out')
    op.drop_column('amenity', 'doorman')
    op.drop_column('amenity', 'conference_room')
    op.drop_column('amenity', 'child_baby_cot')
    op.drop_column('amenity', 'banquets')
    op.drop_column('amenity', 'Room_cleaning_service')
    # ### end Alembic commands ###
