"""empty message

Revision ID: 53f1185d87c3
Revises: 
Create Date: 2018-06-12 18:35:15.908696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53f1185d87c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stay',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('distance', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('rating_label', sa.String(), nullable=True),
    sa.Column('wifi', sa.String(), nullable=True),
    sa.Column('star', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stay_id'), 'stay', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stay_id'), table_name='stay')
    op.drop_table('stay')
    # ### end Alembic commands ###
