"""empty message

Revision ID: 565bfdcbb0d8
Revises: 9ce7dc3f7ffe
Create Date: 2018-06-16 17:46:44.025440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '565bfdcbb0d8'
down_revision = '9ce7dc3f7ffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_id'), 'image', ['id'], unique=False)
    op.create_table('facility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bathroom_with_shower', sa.Boolean(), nullable=True),
    sa.Column('bathroom_nightie', sa.Boolean(), nullable=True),
    sa.Column('wardrobes_closet', sa.Boolean(), nullable=True),
    sa.Column('room_slipper', sa.Boolean(), nullable=True),
    sa.Column('morning_newspaper', sa.Boolean(), nullable=True),
    sa.Column('food_serve_at_room', sa.Boolean(), nullable=True),
    sa.Column('ironing_facility', sa.Boolean(), nullable=True),
    sa.Column('view', sa.Boolean(), nullable=True),
    sa.Column('free_toiletries', sa.Boolean(), nullable=True),
    sa.Column('bathroom_towels', sa.Boolean(), nullable=True),
    sa.Column('bathroom_cosmetics', sa.Boolean(), nullable=True),
    sa.Column('weighing_machine', sa.Boolean(), nullable=True),
    sa.Column('room_seating_area', sa.Boolean(), nullable=True),
    sa.Column('room_slippers', sa.Boolean(), nullable=True),
    sa.Column('free_evening_snacks', sa.Boolean(), nullable=True),
    sa.Column('ac', sa.Boolean(), nullable=True),
    sa.Column('hairdryer', sa.Boolean(), nullable=True),
    sa.Column('wifi', sa.Boolean(), nullable=True),
    sa.Column('tv', sa.Boolean(), nullable=True),
    sa.Column('phone', sa.Boolean(), nullable=True),
    sa.Column('room_safe', sa.Boolean(), nullable=True),
    sa.Column('heater', sa.Boolean(), nullable=True),
    sa.Column('desk', sa.Boolean(), nullable=True),
    sa.Column('fan', sa.Boolean(), nullable=True),
    sa.Column('electric_kettle', sa.Boolean(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id')
    )
    op.create_index(op.f('ix_facility_id'), 'facility', ['id'], unique=False)
    op.add_column('hotel', sa.Column('desc', sa.Text(), nullable=True))
    op.drop_column('hotel', 'images')
    op.add_column('room', sa.Column('image', sa.String(), nullable=True))
    op.drop_column('room', 'wifi')
    op.drop_column('room', 'fan')
    op.drop_column('room', 'room_safe')
    op.drop_column('room', 'electric_kettle')
    op.drop_column('room', 'desk')
    op.drop_column('room', 'phone')
    op.drop_column('room', 'hairdryer')
    op.drop_column('room', 'heater')
    op.drop_column('room', 'tv')
    op.drop_column('room', 'ac')
    op.drop_column('room', 'images')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('images', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('room', sa.Column('ac', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('room', sa.Column('tv', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('room', sa.Column('heater', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('room', sa.Column('hairdryer', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('room', sa.Column('phone', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('room', sa.Column('desk', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('room', sa.Column('electric_kettle', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('room', sa.Column('room_safe', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('room', sa.Column('fan', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('room', sa.Column('wifi', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('room', 'image')
    op.add_column('hotel', sa.Column('images', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('hotel', 'desc')
    op.drop_index(op.f('ix_facility_id'), table_name='facility')
    op.drop_table('facility')
    op.drop_index(op.f('ix_image_id'), table_name='image')
    op.drop_table('image')
    # ### end Alembic commands ###
