"""empty message

Revision ID: 56f8c3edcec8
Revises: 7b35352a5cbe
Create Date: 2018-06-21 22:48:39.347378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56f8c3edcec8'
down_revision = '7b35352a5cbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facility', sa.Column('breakfast', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facility', 'breakfast')
    # ### end Alembic commands ###
