"""empty message

Revision ID: 5e177719a2f0
Revises: 7d536e7664c0
Create Date: 2018-07-05 00:39:11.779566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e177719a2f0'
down_revision = '7d536e7664c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('other_room_type', sa.String(), nullable=True))
    op.drop_column('room', 'default_room_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('default_room_type', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('room', 'other_room_type')
    # ### end Alembic commands ###
