"""empty message

Revision ID: 71d9d0f406f9
Revises: de478c5caa57
Create Date: 2018-07-28 12:58:09.322283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71d9d0f406f9'
down_revision = 'de478c5caa57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('association_dish_id_fkey', 'association', type_='foreignkey')
    op.drop_column('association', 'dish_id')
    op.add_column('dish', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dish', 'restaurant', ['restaurant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dish', type_='foreignkey')
    op.drop_column('dish', 'restaurant_id')
    op.add_column('association', sa.Column('dish_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('association_dish_id_fkey', 'association', 'dish', ['dish_id'], ['id'])
    # ### end Alembic commands ###
