"""empty message

Revision ID: 7226c1d72391
Revises: a1bee80df33d
Create Date: 2018-08-15 00:20:03.294753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7226c1d72391'
down_revision = 'a1bee80df33d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cab_booking', sa.Column('booking_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('cab_booking', sa.Column('booking_status', sa.Integer(), nullable=True))
    op.add_column('cab_booking', sa.Column('cab_booking_id', sa.String(), nullable=True))
    op.add_column('cab_booking', sa.Column('mode_of_payment', sa.Integer(), nullable=True))
    op.add_column('cab_booking', sa.Column('total_distance', sa.DECIMAL(), nullable=True))
    op.add_column('cab_booking', sa.Column('total_fare', sa.DECIMAL(), nullable=True))
    op.add_column('cab_booking', sa.Column('total_hours', sa.Integer(), nullable=True))
    op.drop_column('cab_deal', 'distance')
    op.drop_column('cab_deal', 'total_hours')
    op.drop_column('cab_deal', 'total_fare')
    op.add_column('cab_tax', sa.Column('booking_id', sa.Integer(), nullable=True))
    op.add_column('cab_tax', sa.Column('i_gst', sa.DECIMAL(), nullable=True))
    op.drop_constraint('cab_tax_deal_id_key', 'cab_tax', type_='unique')
    op.create_unique_constraint(None, 'cab_tax', ['booking_id'])
    op.drop_constraint('cab_tax_deal_id_fkey', 'cab_tax', type_='foreignkey')
    op.create_foreign_key(None, 'cab_tax', 'cab_booking', ['booking_id'], ['id'])
    op.drop_column('cab_tax', 'deal_id')
    op.drop_column('restaurant', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cab_tax', sa.Column('deal_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cab_tax', type_='foreignkey')
    op.create_foreign_key('cab_tax_deal_id_fkey', 'cab_tax', 'cab_deal', ['deal_id'], ['id'])
    op.drop_constraint(None, 'cab_tax', type_='unique')
    op.create_unique_constraint('cab_tax_deal_id_key', 'cab_tax', ['deal_id'])
    op.drop_column('cab_tax', 'i_gst')
    op.drop_column('cab_tax', 'booking_id')
    op.add_column('cab_deal', sa.Column('total_fare', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('cab_deal', sa.Column('total_hours', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('cab_deal', sa.Column('distance', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_column('cab_booking', 'total_hours')
    op.drop_column('cab_booking', 'total_fare')
    op.drop_column('cab_booking', 'total_distance')
    op.drop_column('cab_booking', 'mode_of_payment')
    op.drop_column('cab_booking', 'cab_booking_id')
    op.drop_column('cab_booking', 'booking_status')
    op.drop_column('cab_booking', 'booking_date')
    # ### end Alembic commands ###
