"""empty message

Revision ID: 7ac2feb7edd8
Revises: 884a6be6e9f5
Create Date: 2018-07-24 14:13:01.181529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ac2feb7edd8'
down_revision = '884a6be6e9f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('dish_type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dish', 'dish_type')
    # ### end Alembic commands ###
