"""empty message

Revision ID: 7d536e7664c0
Revises: 4050ba1a7569
Create Date: 2018-07-03 20:12:11.737961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d536e7664c0'
down_revision = '4050ba1a7569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotel', sa.Column('latitude', sa.Float(asdecimal=True), nullable=True))
    op.add_column('hotel', sa.Column('longitude', sa.Float(asdecimal=True), nullable=True))
    op.add_column('room', sa.Column('default_room_type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'default_room_type')
    op.drop_column('hotel', 'longitude')
    op.drop_column('hotel', 'latitude')
    # ### end Alembic commands ###
