"""empty message

Revision ID: 7ff3a07f92a5
Revises: 
Create Date: 2018-07-31 12:07:46.252940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ff3a07f92a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('car_name', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('car_type', sa.Integer(), nullable=True),
    sa.Column('cab_type', sa.Integer(), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cab_id'), 'cab', ['id'], unique=False)
    op.create_table('cab_website',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('logo_image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cab_website_id'), 'cab_website', ['id'], unique=False)
    op.create_table('collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collection', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_id'), 'collection', ['id'], unique=False)
    op.create_table('cuisine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cuisine', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cuisine_id'), 'cuisine', ['id'], unique=False)
    op.create_table('hotel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('star', sa.Integer(), nullable=True),
    sa.Column('rating', sa.DECIMAL(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(asdecimal=True), nullable=True),
    sa.Column('longitude', sa.Float(asdecimal=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_hotel_id'), 'hotel', ['id'], unique=False)
    op.create_table('restaurant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('rating', sa.DECIMAL(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(asdecimal=True), nullable=True),
    sa.Column('longitude', sa.Float(asdecimal=True), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_restaurant_id'), 'restaurant', ['id'], unique=False)
    op.create_table('website',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('logo_image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_id'), 'website', ['id'], unique=False)
    op.create_table('amenity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('conference_room', sa.Boolean(), nullable=True),
    sa.Column('parking', sa.Boolean(), nullable=True),
    sa.Column('couple_friendly', sa.Boolean(), nullable=True),
    sa.Column('express_check_in_out', sa.Boolean(), nullable=True),
    sa.Column('laundry_service', sa.Boolean(), nullable=True),
    sa.Column('indoor_swimming_pool', sa.Boolean(), nullable=True),
    sa.Column('outdoor_swimming_pool', sa.Boolean(), nullable=True),
    sa.Column('porter_service', sa.Boolean(), nullable=True),
    sa.Column('Room_cleaning_service', sa.Boolean(), nullable=True),
    sa.Column('terrace', sa.Boolean(), nullable=True),
    sa.Column('child_baby_cot', sa.Boolean(), nullable=True),
    sa.Column('wheelchair_accessible', sa.Boolean(), nullable=True),
    sa.Column('doorman', sa.Boolean(), nullable=True),
    sa.Column('hairdresser', sa.Boolean(), nullable=True),
    sa.Column('banquets', sa.Boolean(), nullable=True),
    sa.Column('non_smoking_smoking_rooms', sa.Boolean(), nullable=True),
    sa.Column('pet_allowance', sa.Boolean(), nullable=True),
    sa.Column('lift', sa.Boolean(), nullable=True),
    sa.Column('bar', sa.Boolean(), nullable=True),
    sa.Column('gym', sa.Boolean(), nullable=True),
    sa.Column('pool', sa.Boolean(), nullable=True),
    sa.Column('restaurant', sa.Boolean(), nullable=True),
    sa.Column('spa', sa.Boolean(), nullable=True),
    sa.Column('wifi_in_lobby', sa.Boolean(), nullable=True),
    sa.Column('twenty_four_hr_reception', sa.Boolean(), nullable=True),
    sa.Column('twenty_four_hr_room_service', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hotel_id')
    )
    op.create_index(op.f('ix_amenity_id'), 'amenity', ['id'], unique=False)
    op.create_table('cab_amenity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cab_id', sa.Integer(), nullable=True),
    sa.Column('air_condition', sa.Boolean(), nullable=True),
    sa.Column('seater', sa.Integer(), nullable=True),
    sa.Column('baggage_allowance', sa.Boolean(), nullable=True),
    sa.Column('doorstep_delivery', sa.Boolean(), nullable=True),
    sa.Column('fuel', sa.Boolean(), nullable=True),
    sa.Column('fuel_type', sa.Integer(), nullable=True),
    sa.Column('fuel_capacity', sa.Integer(), nullable=True),
    sa.Column('automatic', sa.Boolean(), nullable=True),
    sa.Column('chauffeur', sa.Boolean(), nullable=True),
    sa.Column('verified_driver', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cab_id'], ['cab.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cab_id')
    )
    op.create_index(op.f('ix_cab_amenity_id'), 'cab_amenity', ['id'], unique=False)
    op.create_table('cab_booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cab_id', sa.Integer(), nullable=True),
    sa.Column('one_way', sa.Boolean(), nullable=True),
    sa.Column('pickup_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('drop_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('outstation', sa.Boolean(), nullable=True),
    sa.Column('drop_latitude', sa.Float(asdecimal=True), nullable=True),
    sa.Column('drop_longitude', sa.Float(asdecimal=True), nullable=True),
    sa.Column('pickup_latitude', sa.Float(asdecimal=True), nullable=True),
    sa.Column('pickup_longitude', sa.Float(asdecimal=True), nullable=True),
    sa.ForeignKeyConstraint(['cab_id'], ['cab.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cab_booking_id'), 'cab_booking', ['id'], unique=False)
    op.create_table('cab_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cab_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cab_id'], ['cab.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cab_image_id'), 'cab_image', ['id'], unique=False)
    op.create_table('dish',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('dish', sa.String(), nullable=True),
    sa.Column('dish_type', sa.String(), nullable=True),
    sa.Column('half_price', sa.Integer(), nullable=True),
    sa.Column('full_price', sa.Integer(), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dish_id'), 'dish', ['id'], unique=False)
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_id'), 'image', ['id'], unique=False)
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('breakfast', sa.Boolean(), nullable=True),
    sa.Column('lunch', sa.Boolean(), nullable=True),
    sa.Column('dinner', sa.Boolean(), nullable=True),
    sa.Column('cafe', sa.Boolean(), nullable=True),
    sa.Column('lounge', sa.Boolean(), nullable=True),
    sa.Column('family', sa.Boolean(), nullable=True),
    sa.Column('bars', sa.Boolean(), nullable=True),
    sa.Column('nightlife', sa.Boolean(), nullable=True),
    sa.Column('street_stalls', sa.Boolean(), nullable=True),
    sa.Column('pocket_friendly', sa.Boolean(), nullable=True),
    sa.Column('diet', sa.Boolean(), nullable=True),
    sa.Column('luxury', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id')
    )
    op.create_index(op.f('ix_menu_id'), 'menu', ['id'], unique=False)
    op.create_table('restaurant_amenity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('home_delivery', sa.Boolean(), nullable=True),
    sa.Column('private_dining_area_available', sa.Boolean(), nullable=True),
    sa.Column('kid_friendly', sa.Boolean(), nullable=True),
    sa.Column('table_reservation_required', sa.Boolean(), nullable=True),
    sa.Column('table_booking_recommended', sa.Boolean(), nullable=True),
    sa.Column('wheelchair_accessible', sa.Boolean(), nullable=True),
    sa.Column('buffet', sa.Boolean(), nullable=True),
    sa.Column('wifi', sa.Boolean(), nullable=True),
    sa.Column('live_entertainment', sa.Boolean(), nullable=True),
    sa.Column('live_music', sa.Boolean(), nullable=True),
    sa.Column('live_sports_screening', sa.Boolean(), nullable=True),
    sa.Column('valet_parking', sa.Boolean(), nullable=True),
    sa.Column('parking', sa.Boolean(), nullable=True),
    sa.Column('group_meal', sa.Boolean(), nullable=True),
    sa.Column('smoking_area', sa.Boolean(), nullable=True),
    sa.Column('desserts_and_bakes', sa.Boolean(), nullable=True),
    sa.Column('full_bar_available', sa.Boolean(), nullable=True),
    sa.Column('serves_jain_food', sa.Boolean(), nullable=True),
    sa.Column('vegetarian_only', sa.Boolean(), nullable=True),
    sa.Column('serves_non_veg', sa.Boolean(), nullable=True),
    sa.Column('nightlife', sa.Boolean(), nullable=True),
    sa.Column('city_view', sa.Boolean(), nullable=True),
    sa.Column('brunch', sa.Boolean(), nullable=True),
    sa.Column('sunday_roast', sa.Boolean(), nullable=True),
    sa.Column('gastro_pub', sa.Boolean(), nullable=True),
    sa.Column('beer', sa.Boolean(), nullable=True),
    sa.Column('outdoor_seating', sa.Boolean(), nullable=True),
    sa.Column('takeaway', sa.Boolean(), nullable=True),
    sa.Column('alcohol', sa.Boolean(), nullable=True),
    sa.Column('seating', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id')
    )
    op.create_index(op.f('ix_restaurant_amenity_id'), 'restaurant_amenity', ['id'], unique=False)
    op.create_table('restaurant_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('cuisine_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['cuisine_id'], ['cuisine.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurant_association_id'), 'restaurant_association', ['id'], unique=False)
    op.create_table('restaurant_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('image_type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurant_image_id'), 'restaurant_image', ['id'], unique=False)
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('room_type', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('other_room_type', sa.String(), nullable=True),
    sa.Column('check_in', sa.DateTime(timezone=True), nullable=False),
    sa.Column('check_out', sa.DateTime(timezone=True), nullable=False),
    sa.Column('breakfast', sa.Boolean(), nullable=True),
    sa.Column('balcony', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_id'), 'room', ['id'], unique=False)
    op.create_table('cab_invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('website_id', sa.Integer(), nullable=True),
    sa.Column('slab', sa.Integer(), nullable=True),
    sa.Column('driver_night_allowance_charge', sa.DECIMAL(), nullable=True),
    sa.Column('car_night_allowance_charge', sa.DECIMAL(), nullable=True),
    sa.Column('total_hours', sa.Integer(), nullable=True),
    sa.Column('base_fare', sa.DECIMAL(), nullable=True),
    sa.Column('base_fare_weekend', sa.DECIMAL(), nullable=True),
    sa.Column('base_fare_peak_season', sa.DECIMAL(), nullable=True),
    sa.Column('base_fare_with_fuel', sa.DECIMAL(), nullable=True),
    sa.Column('different_pickup_drop_point_charge', sa.DECIMAL(), nullable=True),
    sa.Column('km_restriction', sa.DECIMAL(), nullable=True),
    sa.Column('fare_exceeded_per_hr', sa.DECIMAL(), nullable=True),
    sa.Column('fare_exceeded_per_km', sa.DECIMAL(), nullable=True),
    sa.Column('initial_km', sa.Integer(), nullable=True),
    sa.Column('initial_km_fare', sa.DECIMAL(), nullable=True),
    sa.Column('cancellation_charges', sa.DECIMAL(), nullable=True),
    sa.Column('distance', sa.DECIMAL(), nullable=True),
    sa.Column('total_fare', sa.DECIMAL(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['cab_booking.id'], ),
    sa.ForeignKeyConstraint(['website_id'], ['cab_website.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cab_invoice_id'), 'cab_invoice', ['id'], unique=False)
    op.create_table('deal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('hotel_url', sa.String(), nullable=True),
    sa.Column('weekend', sa.Boolean(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['website_id'], ['website.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_id'), 'deal', ['id'], unique=False)
    op.create_table('facility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bed_type', sa.Integer(), nullable=True),
    sa.Column('no_of_bed', sa.Integer(), nullable=True),
    sa.Column('bathroom_with_shower', sa.Boolean(), nullable=True),
    sa.Column('bathroom_nightie', sa.Boolean(), nullable=True),
    sa.Column('wardrobes_closet', sa.Boolean(), nullable=True),
    sa.Column('room_slipper', sa.Boolean(), nullable=True),
    sa.Column('morning_newspaper', sa.Boolean(), nullable=True),
    sa.Column('food_serve_at_room', sa.Boolean(), nullable=True),
    sa.Column('ironing_facility', sa.Boolean(), nullable=True),
    sa.Column('view', sa.Boolean(), nullable=True),
    sa.Column('free_toiletries', sa.Boolean(), nullable=True),
    sa.Column('bathroom_towels', sa.Boolean(), nullable=True),
    sa.Column('bathroom_cosmetics', sa.Boolean(), nullable=True),
    sa.Column('weighing_machine', sa.Boolean(), nullable=True),
    sa.Column('room_seating_area', sa.Boolean(), nullable=True),
    sa.Column('free_evening_snacks', sa.Boolean(), nullable=True),
    sa.Column('ac', sa.Boolean(), nullable=True),
    sa.Column('hairdryer', sa.Boolean(), nullable=True),
    sa.Column('wifi', sa.Boolean(), nullable=True),
    sa.Column('tv', sa.Boolean(), nullable=True),
    sa.Column('phone', sa.Boolean(), nullable=True),
    sa.Column('room_safe', sa.Boolean(), nullable=True),
    sa.Column('heater', sa.Boolean(), nullable=True),
    sa.Column('desk', sa.Boolean(), nullable=True),
    sa.Column('fan', sa.Boolean(), nullable=True),
    sa.Column('electric_kettle', sa.Boolean(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id')
    )
    op.create_index(op.f('ix_facility_id'), 'facility', ['id'], unique=False)
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('no_of_adults', sa.Integer(), nullable=True),
    sa.Column('children', sa.Integer(), nullable=True),
    sa.Column('total_members', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id')
    )
    op.create_index(op.f('ix_member_id'), 'member', ['id'], unique=False)
    op.create_table('cab_tax',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('gst', sa.DECIMAL(), nullable=True),
    sa.Column('s_gst', sa.DECIMAL(), nullable=True),
    sa.Column('c_gst', sa.DECIMAL(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['cab_invoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cab_tax_id'), 'cab_tax', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cab_tax_id'), table_name='cab_tax')
    op.drop_table('cab_tax')
    op.drop_index(op.f('ix_member_id'), table_name='member')
    op.drop_table('member')
    op.drop_index(op.f('ix_facility_id'), table_name='facility')
    op.drop_table('facility')
    op.drop_index(op.f('ix_deal_id'), table_name='deal')
    op.drop_table('deal')
    op.drop_index(op.f('ix_cab_invoice_id'), table_name='cab_invoice')
    op.drop_table('cab_invoice')
    op.drop_index(op.f('ix_room_id'), table_name='room')
    op.drop_table('room')
    op.drop_index(op.f('ix_restaurant_image_id'), table_name='restaurant_image')
    op.drop_table('restaurant_image')
    op.drop_index(op.f('ix_restaurant_association_id'), table_name='restaurant_association')
    op.drop_table('restaurant_association')
    op.drop_index(op.f('ix_restaurant_amenity_id'), table_name='restaurant_amenity')
    op.drop_table('restaurant_amenity')
    op.drop_index(op.f('ix_menu_id'), table_name='menu')
    op.drop_table('menu')
    op.drop_index(op.f('ix_image_id'), table_name='image')
    op.drop_table('image')
    op.drop_index(op.f('ix_dish_id'), table_name='dish')
    op.drop_table('dish')
    op.drop_index(op.f('ix_cab_image_id'), table_name='cab_image')
    op.drop_table('cab_image')
    op.drop_index(op.f('ix_cab_booking_id'), table_name='cab_booking')
    op.drop_table('cab_booking')
    op.drop_index(op.f('ix_cab_amenity_id'), table_name='cab_amenity')
    op.drop_table('cab_amenity')
    op.drop_index(op.f('ix_amenity_id'), table_name='amenity')
    op.drop_table('amenity')
    op.drop_index(op.f('ix_website_id'), table_name='website')
    op.drop_table('website')
    op.drop_index(op.f('ix_restaurant_id'), table_name='restaurant')
    op.drop_table('restaurant')
    op.drop_index(op.f('ix_hotel_id'), table_name='hotel')
    op.drop_table('hotel')
    op.drop_index(op.f('ix_cuisine_id'), table_name='cuisine')
    op.drop_table('cuisine')
    op.drop_index(op.f('ix_collection_id'), table_name='collection')
    op.drop_table('collection')
    op.drop_index(op.f('ix_cab_website_id'), table_name='cab_website')
    op.drop_table('cab_website')
    op.drop_index(op.f('ix_cab_id'), table_name='cab')
    op.drop_table('cab')
    # ### end Alembic commands ###
