"""empty message

Revision ID: 804e432b213b
Revises: eb3aa28fb610
Create Date: 2018-06-21 22:11:45.194884

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '804e432b213b'
down_revision = 'eb3aa28fb610'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bathroom_with_shower', sa.Boolean(), nullable=True),
    sa.Column('bathroom_nightie', sa.Boolean(), nullable=True),
    sa.Column('balcony', sa.Boolean(), nullable=True),
    sa.Column('wardrobes_closet', sa.Boolean(), nullable=True),
    sa.Column('room_slipper', sa.Boolean(), nullable=True),
    sa.Column('morning_newspaper', sa.Boolean(), nullable=True),
    sa.Column('food_serve_at_room', sa.Boolean(), nullable=True),
    sa.Column('ironing_facility', sa.Boolean(), nullable=True),
    sa.Column('view', sa.Boolean(), nullable=True),
    sa.Column('free_toiletries', sa.Boolean(), nullable=True),
    sa.Column('bathroom_towels', sa.Boolean(), nullable=True),
    sa.Column('bathroom_cosmetics', sa.Boolean(), nullable=True),
    sa.Column('weighing_machine', sa.Boolean(), nullable=True),
    sa.Column('room_seating_area', sa.Boolean(), nullable=True),
    sa.Column('free_evening_snacks', sa.Boolean(), nullable=True),
    sa.Column('ac', sa.Boolean(), nullable=True),
    sa.Column('hairdryer', sa.Boolean(), nullable=True),
    sa.Column('wifi', sa.Boolean(), nullable=True),
    sa.Column('tv', sa.Boolean(), nullable=True),
    sa.Column('phone', sa.Boolean(), nullable=True),
    sa.Column('room_safe', sa.Boolean(), nullable=True),
    sa.Column('heater', sa.Boolean(), nullable=True),
    sa.Column('desk', sa.Boolean(), nullable=True),
    sa.Column('fan', sa.Boolean(), nullable=True),
    sa.Column('electric_kettle', sa.Boolean(), nullable=True),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hotel_id')
    )
    op.create_index(op.f('ix_facility_id'), 'facility', ['id'], unique=False)
    op.drop_table('room_facility')
    op.add_column('price', sa.Column('weekend', sa.Boolean(), nullable=True))
    op.drop_column('price', 'avg_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price', sa.Column('avg_price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('price', 'weekend')
    op.create_table('room_facility',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('bathroom_with_shower', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('bathroom_nightie', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('wardrobes_closet', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('room_slipper', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('morning_newspaper', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('food_serve_at_room', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ironing_facility', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('view', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('free_toiletries', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('bathroom_towels', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('bathroom_cosmetics', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('weighing_machine', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('room_seating_area', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('free_evening_snacks', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ac', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('hairdryer', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('wifi', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('tv', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('room_safe', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('heater', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('desk', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('fan', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('electric_kettle', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('hotel_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('balcony', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.id'], name='room_facility_hotel_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='room_facility_pkey'),
    sa.UniqueConstraint('hotel_id', name='room_facility_hotel_id_key')
    )
    op.drop_index(op.f('ix_facility_id'), table_name='facility')
    op.drop_table('facility')
    # ### end Alembic commands ###
