"""empty message

Revision ID: 836fab5afe04
Revises: 
Create Date: 2018-06-24 19:21:40.257910

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '836fab5afe04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('room_type', sa.Integer(), nullable=True),
    sa.Column('check_in', sa.DateTime(timezone=True), nullable=False),
    sa.Column('check_out', sa.DateTime(timezone=True), nullable=False),
    sa.Column('breakfast', sa.Boolean(), nullable=True),
    sa.Column('balcony', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_id'), 'room', ['id'], unique=False)
    op.add_column('amenity', sa.Column('hotel_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'amenity', ['hotel_id'])
    op.create_foreign_key(None, 'amenity', 'hotel', ['hotel_id'], ['id'])
    op.add_column('deal', sa.Column('room_id', sa.Integer(), nullable=True))
    op.drop_constraint('deal_hotel_id_fkey', 'deal', type_='foreignkey')
    op.create_foreign_key(None, 'deal', 'room', ['room_id'], ['id'])
    op.drop_column('deal', 'hotel_id')
    op.add_column('facility', sa.Column('room_id', sa.Integer(), nullable=True))
    op.drop_constraint('facility_hotel_id_key', 'facility', type_='unique')
    op.create_unique_constraint(None, 'facility', ['room_id'])
    op.drop_constraint('facility_hotel_id_fkey', 'facility', type_='foreignkey')
    op.create_foreign_key(None, 'facility', 'room', ['room_id'], ['id'])
    op.drop_column('facility', 'hotel_id')
    op.drop_constraint('hotel_amenity_id_fkey', 'hotel', type_='foreignkey')
    op.drop_constraint('hotel_image_id_fkey', 'hotel', type_='foreignkey')
    op.drop_column('hotel', 'check_in')
    op.drop_column('hotel', 'amenity_id')
    op.drop_column('hotel', 'room_type')
    op.drop_column('hotel', 'check_out')
    op.drop_column('hotel', 'balcony')
    op.drop_column('hotel', 'image_id')
    op.drop_column('hotel', 'status')
    op.drop_column('hotel', 'breakfast')
    op.add_column('image', sa.Column('hotel_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'image', 'hotel', ['hotel_id'], ['id'])
    op.add_column('member', sa.Column('room_id', sa.Integer(), nullable=True))
    op.drop_constraint('member_hotel_id_key', 'member', type_='unique')
    op.create_unique_constraint(None, 'member', ['room_id'])
    op.drop_constraint('member_hotel_id_fkey', 'member', type_='foreignkey')
    op.create_foreign_key(None, 'member', 'room', ['room_id'], ['id'])
    op.drop_column('member', 'hotel_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('hotel_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'member', type_='foreignkey')
    op.create_foreign_key('member_hotel_id_fkey', 'member', 'hotel', ['hotel_id'], ['id'])
    op.drop_constraint(None, 'member', type_='unique')
    op.create_unique_constraint('member_hotel_id_key', 'member', ['hotel_id'])
    op.drop_column('member', 'room_id')
    op.drop_constraint(None, 'image', type_='foreignkey')
    op.drop_column('image', 'hotel_id')
    op.add_column('hotel', sa.Column('breakfast', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('hotel', sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('hotel', sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('hotel', sa.Column('balcony', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('hotel', sa.Column('check_out', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('hotel', sa.Column('room_type', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('hotel', sa.Column('amenity_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('hotel', sa.Column('check_in', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.create_foreign_key('hotel_image_id_fkey', 'hotel', 'image', ['image_id'], ['id'])
    op.create_foreign_key('hotel_amenity_id_fkey', 'hotel', 'amenity', ['amenity_id'], ['id'])
    op.add_column('facility', sa.Column('hotel_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'facility', type_='foreignkey')
    op.create_foreign_key('facility_hotel_id_fkey', 'facility', 'hotel', ['hotel_id'], ['id'])
    op.drop_constraint(None, 'facility', type_='unique')
    op.create_unique_constraint('facility_hotel_id_key', 'facility', ['hotel_id'])
    op.drop_column('facility', 'room_id')
    op.add_column('deal', sa.Column('hotel_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'deal', type_='foreignkey')
    op.create_foreign_key('deal_hotel_id_fkey', 'deal', 'hotel', ['hotel_id'], ['id'])
    op.drop_column('deal', 'room_id')
    op.drop_constraint(None, 'amenity', type_='foreignkey')
    op.drop_constraint(None, 'amenity', type_='unique')
    op.drop_column('amenity', 'hotel_id')
    op.drop_index(op.f('ix_room_id'), table_name='room')
    op.drop_table('room')
    # ### end Alembic commands ###
