"""empty message

Revision ID: 884a6be6e9f5
Revises: 4012320fd1d0
Create Date: 2018-07-24 00:59:33.926803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '884a6be6e9f5'
down_revision = '4012320fd1d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('desc', sa.Text(), nullable=True))
    op.add_column('dish', sa.Column('full_price', sa.Integer(), nullable=True))
    op.add_column('dish', sa.Column('half_price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dish', 'half_price')
    op.drop_column('dish', 'full_price')
    op.drop_column('dish', 'desc')
    # ### end Alembic commands ###
