"""empty message

Revision ID: 97b94326c2c3
Revises: 37439bfa0a67
Create Date: 2018-06-23 21:07:51.777568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97b94326c2c3'
down_revision = '37439bfa0a67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'facility', ['hotel_id'])
    op.drop_column('facility', 'balcony')
    op.drop_column('facility', 'breakfast')
    op.add_column('hotel', sa.Column('balcony', sa.Boolean(), nullable=True))
    op.add_column('hotel', sa.Column('breakfast', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotel', 'breakfast')
    op.drop_column('hotel', 'balcony')
    op.add_column('facility', sa.Column('breakfast', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('facility', sa.Column('balcony', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'facility', type_='unique')
    # ### end Alembic commands ###
