"""empty message

Revision ID: 9a5aa55437fd
Revises: 6deaf8206030
Create Date: 2018-08-01 23:31:04.660226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a5aa55437fd'
down_revision = '6deaf8206030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('desc', sa.Text(), nullable=True))
    op.add_column('collection', sa.Column('featured', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'featured')
    op.drop_column('collection', 'desc')
    # ### end Alembic commands ###
