"""empty message

Revision ID: 9ce7dc3f7ffe
Revises: a06194b298a1
Create Date: 2018-06-16 01:43:13.091338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9ce7dc3f7ffe'
down_revision = 'a06194b298a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('website_hotel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('website_id', sa.Integer(), nullable=True),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.id'], ),
    sa.ForeignKeyConstraint(['website_id'], ['website.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_hotel_id'), 'website_hotel', ['id'], unique=False)
    op.drop_table('website_room')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('website_room',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('website_room_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('website_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], name='website_room_room_id_fkey'),
    sa.ForeignKeyConstraint(['website_id'], ['website.id'], name='website_room_website_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'website_room_id', name='website_room_pkey')
    )
    op.drop_index(op.f('ix_website_hotel_id'), table_name='website_hotel')
    op.drop_table('website_hotel')
    # ### end Alembic commands ###
