"""empty message

Revision ID: a06194b298a1
Revises: c711edff2a22
Create Date: 2018-06-16 01:28:08.945404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a06194b298a1'
down_revision = 'c711edff2a22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price', sa.Column('room_id', sa.Integer(), nullable=True))
    op.add_column('price', sa.Column('website_id', sa.Integer(), nullable=True))
    op.drop_constraint('price_website_room_id_fkey', 'price', type_='foreignkey')
    op.create_foreign_key(None, 'price', 'website', ['website_id'], ['id'])
    op.create_foreign_key(None, 'price', 'room', ['room_id'], ['id'])
    op.drop_column('price', 'website_room_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price', sa.Column('website_room_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'price', type_='foreignkey')
    op.drop_constraint(None, 'price', type_='foreignkey')
    op.create_foreign_key('price_website_room_id_fkey', 'price', 'website_room', ['website_room_id'], ['website_room_id'])
    op.drop_column('price', 'website_id')
    op.drop_column('price', 'room_id')
    # ### end Alembic commands ###
