"""empty message

Revision ID: ab7015bd1fd0
Revises: 7ff3a07f92a5
Create Date: 2018-08-01 00:41:33.140143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab7015bd1fd0'
down_revision = '7ff3a07f92a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('especially', sa.Text(), nullable=True))
    op.add_column('restaurant', sa.Column('nearest_metro_station', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant', 'nearest_metro_station')
    op.drop_column('restaurant', 'especially')
    # ### end Alembic commands ###
