"""empty message

Revision ID: be31743bbf7f
Revises: 7d58800f4200
Create Date: 2018-07-30 13:57:49.836928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be31743bbf7f'
down_revision = '7d58800f4200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_amenity', sa.Column('gastro_pub', sa.Boolean(), nullable=True))
    op.drop_column('restaurant_amenity', 'gastro_Pub')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_amenity', sa.Column('gastro_Pub', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('restaurant_amenity', 'gastro_pub')
    # ### end Alembic commands ###
