"""empty message

Revision ID: c711edff2a22
Revises: 3d1a649fe4bd
Create Date: 2018-06-16 01:17:19.520570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c711edff2a22'
down_revision = '3d1a649fe4bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'amenity', ['hotel_id'])
    op.create_unique_constraint(None, 'member', ['room_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'member', type_='unique')
    op.drop_constraint(None, 'amenity', type_='unique')
    # ### end Alembic commands ###
