"""empty message

Revision ID: cc1b09b3b777
Revises: d90797834389
Create Date: 2018-08-08 16:04:28.881745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc1b09b3b777'
down_revision = 'd90797834389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cab', sa.Column('is_partner', sa.Boolean(), nullable=True))
    op.add_column('cab_deal', sa.Column('cab_url', sa.String(), nullable=True))
    op.add_column('hotel', sa.Column('is_partner', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotel', 'is_partner')
    op.drop_column('cab_deal', 'cab_url')
    op.drop_column('cab', 'is_partner')
    # ### end Alembic commands ###
