"""empty message

Revision ID: d2d8a60ac14c
Revises: 97b94326c2c3
Create Date: 2018-06-24 18:16:54.852309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2d8a60ac14c'
down_revision = '97b94326c2c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('amenity_hotel_id_key', 'amenity', type_='unique')
    op.drop_constraint('amenity_hotel_id_fkey', 'amenity', type_='foreignkey')
    op.drop_column('amenity', 'hotel_id')
    op.add_column('hotel', sa.Column('amenity_id', sa.Integer(), nullable=True))
    op.add_column('hotel', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'hotel', 'amenity', ['amenity_id'], ['id'])
    op.create_foreign_key(None, 'hotel', 'image', ['image_id'], ['id'])
    op.drop_constraint('image_hotel_id_fkey', 'image', type_='foreignkey')
    op.drop_column('image', 'hotel_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('hotel_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('image_hotel_id_fkey', 'image', 'hotel', ['hotel_id'], ['id'])
    op.drop_constraint(None, 'hotel', type_='foreignkey')
    op.drop_constraint(None, 'hotel', type_='foreignkey')
    op.drop_column('hotel', 'image_id')
    op.drop_column('hotel', 'amenity_id')
    op.add_column('amenity', sa.Column('hotel_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('amenity_hotel_id_fkey', 'amenity', 'hotel', ['hotel_id'], ['id'])
    op.create_unique_constraint('amenity_hotel_id_key', 'amenity', ['hotel_id'])
    # ### end Alembic commands ###
