"""empty message

Revision ID: d90797834389
Revises: 25aaae0275d6
Create Date: 2018-08-05 17:32:50.550119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd90797834389'
down_revision = '25aaae0275d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotel', sa.Column('category', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotel', 'category')
    # ### end Alembic commands ###
