"""empty message

Revision ID: de478c5caa57
Revises: 7ac2feb7edd8
Create Date: 2018-07-27 18:48:01.354822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de478c5caa57'
down_revision = '7ac2feb7edd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('car_name', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('car_type', sa.Integer(), nullable=True),
    sa.Column('cab_type', sa.Integer(), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cab_id'), 'cab', ['id'], unique=False)
    op.create_table('cab_amenity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cab_id', sa.Integer(), nullable=True),
    sa.Column('air_condition', sa.Boolean(), nullable=True),
    sa.Column('seater', sa.Integer(), nullable=True),
    sa.Column('baggage_allowance', sa.Boolean(), nullable=True),
    sa.Column('doorstep_delivery', sa.Boolean(), nullable=True),
    sa.Column('fuel', sa.Boolean(), nullable=True),
    sa.Column('fuel_type', sa.Integer(), nullable=True),
    sa.Column('fuel_capacity', sa.Integer(), nullable=True),
    sa.Column('automatic', sa.Boolean(), nullable=True),
    sa.Column('chauffeur', sa.Boolean(), nullable=True),
    sa.Column('verified_driver', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cab_id'], ['cab.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cab_id')
    )
    op.create_index(op.f('ix_cab_amenity_id'), 'cab_amenity', ['id'], unique=False)
    op.create_table('cab_booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cab_id', sa.Integer(), nullable=True),
    sa.Column('one_way', sa.Boolean(), nullable=True),
    sa.Column('pickup_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('drop_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('outstation', sa.Boolean(), nullable=True),
    sa.Column('drop_latitude', sa.Float(asdecimal=True), nullable=True),
    sa.Column('drop_longitude', sa.Float(asdecimal=True), nullable=True),
    sa.Column('pickup_latitude', sa.Float(asdecimal=True), nullable=True),
    sa.Column('pickup_longitude', sa.Float(asdecimal=True), nullable=True),
    sa.ForeignKeyConstraint(['cab_id'], ['cab.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cab_id')
    )
    op.create_index(op.f('ix_cab_booking_id'), 'cab_booking', ['id'], unique=False)
    op.create_table('cab_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cab_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cab_id'], ['cab.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cab_image_id'), 'cab_image', ['id'], unique=False)
    op.create_table('cab_invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cab_id', sa.Integer(), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('slab', sa.Integer(), nullable=True),
    sa.Column('driver_night_allowance_charge', sa.DECIMAL(), nullable=True),
    sa.Column('car_night_allowance_charge', sa.DECIMAL(), nullable=True),
    sa.Column('total_hours', sa.Integer(), nullable=True),
    sa.Column('base_fare', sa.DECIMAL(), nullable=True),
    sa.Column('base_fare_weekend', sa.DECIMAL(), nullable=True),
    sa.Column('base_fare_peak_season', sa.DECIMAL(), nullable=True),
    sa.Column('base_fare_with_fuel', sa.DECIMAL(), nullable=True),
    sa.Column('different_pickup_drop_point_charge', sa.DECIMAL(), nullable=True),
    sa.Column('km_restriction', sa.DECIMAL(), nullable=True),
    sa.Column('fare_exceeded_per_hr', sa.DECIMAL(), nullable=True),
    sa.Column('fare_exceeded_per_km', sa.DECIMAL(), nullable=True),
    sa.Column('initial_km', sa.Integer(), nullable=True),
    sa.Column('initial_km_fare', sa.DECIMAL(), nullable=True),
    sa.Column('cancellation_charges', sa.DECIMAL(), nullable=True),
    sa.Column('distance', sa.DECIMAL(), nullable=True),
    sa.Column('total_fare', sa.DECIMAL(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['cab_booking.id'], ),
    sa.ForeignKeyConstraint(['cab_id'], ['cab.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cab_invoice_id'), 'cab_invoice', ['id'], unique=False)
    op.create_table('cab_tax',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('gst', sa.DECIMAL(), nullable=True),
    sa.Column('s_gst', sa.DECIMAL(), nullable=True),
    sa.Column('c_gst', sa.DECIMAL(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['cab_invoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cab_tax_id'), 'cab_tax', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cab_tax_id'), table_name='cab_tax')
    op.drop_table('cab_tax')
    op.drop_index(op.f('ix_cab_invoice_id'), table_name='cab_invoice')
    op.drop_table('cab_invoice')
    op.drop_index(op.f('ix_cab_image_id'), table_name='cab_image')
    op.drop_table('cab_image')
    op.drop_index(op.f('ix_cab_booking_id'), table_name='cab_booking')
    op.drop_table('cab_booking')
    op.drop_index(op.f('ix_cab_amenity_id'), table_name='cab_amenity')
    op.drop_table('cab_amenity')
    op.drop_index(op.f('ix_cab_id'), table_name='cab')
    op.drop_table('cab')
    # ### end Alembic commands ###
