"""empty message

Revision ID: eb3aa28fb610
Revises: 51a644ea58cc
Create Date: 2018-06-20 23:20:10.028815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb3aa28fb610'
down_revision = '51a644ea58cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_facility', sa.Column('balcony', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_facility', 'balcony')
    # ### end Alembic commands ###
