"""empty message

Revision ID: ee77e156f852
Revises: f39cf2114ba4
Create Date: 2018-06-14 23:24:54.798436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee77e156f852'
down_revision = 'f39cf2114ba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('check_in', sa.DateTime(timezone=True), nullable=False))
    op.add_column('room', sa.Column('check_out', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'check_out')
    op.drop_column('room', 'check_in')
    # ### end Alembic commands ###
